# Generated by Django 5.0.7 on 2024-11-10 11:00

import app.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_version_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(max_length=500, null=True, upload_to=app.utility.file_upload_to),
        ),
    ]
