# Generated by Django 5.0.7 on 2024-11-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_projecttimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttimer',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='projecttimer',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
