export const programmingLanguages = {
    js: "JavaScript",
    ts: "TypeScript",
    py: "Python",
    java: "Java",
    c: "C",
    cpp: "C++",
    cs: "C#",
    rb: "Ruby",
    php: "PHP",
    go: "Go",
    rs: "Rust",
    swift: "Swift",
    kt: "Kotlin",
    html: "HTML",
    css: "CSS",
    sql: "SQL",
    sh: "Shell Script",
    md: "Markdown",
    r: "R",
    pl: "Perl",
    scala: "Scala",
    clj: "Clojure",
    dart: "Dart",
    el: "Elixir",
    lua: "Lua",
    nim: "Nim",
    groovy: "Groovy",
    ml: "ML",
    h: "C Header",
    hpp: "C++ Header",
    asm: "Assembly",
    json: "JSON",
    xml: "XML",
    yml: "YAML",
    yaml: "YAML",
    toml: "TOML",
    bash: "Bash",
    awk: "Awk",
    v: "V",
    f90: "Fortran",
    f: "Fortran",
    vhd: "VHDL",
    sv: "SystemVerilog",
    ps1: "PowerShell",
    psm1: "PowerShell Module",
    erl: "Erlang",
    ex: "Elixir",
    exs: "Elixir Script",
    pike: "Pike",
    applescript: "AppleScript",
    coffee: "CoffeeScript",
    actionscript: "ActionScript",
    scad: "OpenSCAD",
    jl: "Julia",
    kotlin: "Kotlin",
    haxe: "Haxe",
    wml: "WML",
    xquery: "XQuery",
    d: "D",
    glsl: "OpenGL Shading Language",
    cl: "Common Lisp",
    lisp: "Lisp",
    sml: "Standard ML",
    prolog: "Prolog",
    coffeescript: "CoffeeScript"
};
